### ISSUE TITLE
Global env vars

### ISSUE THREAD

**Issue by mpdude** [meeDamian/github-actions-bugs#2]
https://github.community/t5/GitHub-Actions/Support-global-environment-variables/m-p/30488/highlight/true#M445

This suggests that an update is in the making that allows to define env vars at the job level.

**Comment by meeDamian** [comment]
That's amazing!  Thank you for linking it here

**Comment by meeDamian** [comment]
Added a job checking it here https://github.com/meeDamian/github-actions-bugs/commit/41d6a430ecac0f8132c1c79fba4105d7e10600c5.

**Comment by mpdude** [comment]
Nice!

**Comment by meeDamian** [comment]
Seems like the job is now passing - should be working/available :)

**Comment by meeDamian** [comment]
Ugh, still not possible to use shell there :/.

So ex. one can't use it to extract git-tag from ${{GITHUB_REF}}, and have it available throughout…

Gonna reopen, and maybe later write test for that too…

**Comment by mpdude** [comment]
I think your test covers the feature that `env` can be set at the job level?

Regarding the previous comment, what exactly have you been expecting?

Do you want to have a job step (a bash command) that exports env vars for the following steps? If so, try:

```bash
echo '::set-env name=FOO::bar'
```

This *might* work to set `FOO` for subsequent steps to `bar`, and can be issued from shell commands.

```bash
...
run: |
    echo ::set-env name=GIT_TAG::$(git describe --abbrev=0)
    ...
``` 

maybe?

**Comment by meeDamian** [comment]
Yeah, that's one of the options (no3 on my list).  I've described all of the ones I've came up with for now here: https://github.com/lncm/docker-bitcoind/issues/10

I want to do, ex:

```yaml
job-name:
  env:
    VERSION: echo "${GITHUB_REF}" | awk -F/ '{print $NF}'
    DIR: echo "${GITHUB_REF}" | awk -F/ '{print $NF}' | tr -d v | cut -d. -f-2
```

And then be able to use `${VERSION}`, or `${DIR}` in all my steps…

**Comment by meeDamian** [comment]
Wait.  That's actually something else!

Where did you get that command from?

**Comment by meeDamian** [comment]
It works! https://github.com/meeDamian/github-actions-bugs/runs/240682186

Thank you, I had no idea it's possible.

Docs on `set-env` are available here: https://help.github.com/en/articles/development-tools-for-github-actions#set-an-environment-variable-set-env
